model_params:
  name: "FFN_AE"
  latent_dim: 128
  num_layers: 5

exp_params:
  dataset: "MNIST"
  data_path: "../data_mnist"
  lr: 0.001
  batch_size: 128
  num_workers: 2

trainer_params:
  max_epoch: 30
  resume: false
