model_params:
  name: "Vanilla_VAE"
  latent_dim: 32
  kernel_size: 5

exp_params:
  dataset: "MNIST"
  data_path: "../data"
  batch_size: 256
  num_workers: 2
  lr: 0.0005

trainer_params:
  max_epoch: 1
  resume: false
